CREATE SCHEMA IMOBILIARIA;

CREATE TABLE IMOBILIARIA.CLIENTES(
	
    ID_CLIENTE int  PRIMARY KEY AUTO_INCREMENT,
    NOME varchar(100) NOT NULL, 
    CPF varchar(11) NOT NULL,
    VALOR_COMPRA double NOT NULL
);

CREATE TABLE IMOBILIARIAclientes.IMOVEL( 
	ID_IMOVEL int PRIMARY KEY NOT NULL AUTO_INCREMENT,
    TIPO_IMOVEL int,
    LOCALIZACAO varchar(500),
    VALOR double,
    TIPO_LOCAL int
);

CREATE TABLE IMOBILIARIA.FINANCEIRO(
	ID_NEGOCIO int PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_IMOVEL int,
    VALOR double,
    VALOR_COMPRA double
); 



ALTER TABLE IMOBILIARIA.CLIENTES 
ADD CONSTRAINT ID_CLIENTE
  FOREIGN KEY (ID_CLIENTE)
  REFERENCES IMOBILIARIA.FINANCEIRO (ID_NEGOCIO)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  
  
INSERT INTO IMOBILIARIA.CLIENTES(NOME,CPF,VALOR_COMPRA) 
VALUES ('João','12345678910','300000');

INSERT INTO IMOBILIARIA.IMOVEL(TIPO_IMOVEL,LOCALIZACAO,VALOR,TIPO_LOCAL) 
VALUES('1','Rua XV de novembro', '192', 'Videira-SC','450000','1');